build:
    dependencies:
        # "override" to not run inferred "python setup.py install" and
        # "pip install -r requirements.txt"
        override:
            - sudo apt-get install --no-install-recommends -y librrd-dev
    tests:
        before:
            - pip install git+git://github.com/kytos/python-openflow.git
            - pip install git+git://github.com/kytos/kytos.git
