openapi: 3.0.0
info:
  title: kytos/of_stats
  version: 1.0.0
  description: "**Warning**: *This documentation is experimental and will
    change soon.*
    \n
    Provide statistics of openflow switches."

tags:
- name: Ports
- name: Flows

paths:
  /api/kytos/of_stats/v1/{dpid}/ports:
    get:
      summary: Given a switch, list its ports with their latest statistics
      description: "Get the latest statistics of all the ports of a switch
        identified by ``dpid``. Also provide the interface name, **MAC**
        address and **link speed** (bps). Ports that have no statistics
        available are ignored."
      parameters:
        - $ref: '#/components/parameters/dpid'
      tags:
        - Ports
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: Each item contains information about one port
                    items:
                      $ref: '#/components/schemas/Port'

  /api/kytos/of_stats/v1/{dpid}/ports/{port}:
    get:
      summary: Get up to 60 points of each statistic type for a port
      description: Return up to 60 evenly-distributed points from ``start`` to
        ``end`` (defaults from first collected sample until current time).
        Useful for plotting graphs.
      parameters:
        - $ref: '#/components/parameters/dpid'
        - $ref: '#/components/parameters/port'
        - $ref: '#/components/parameters/start_timestamp'
        - $ref: '#/components/parameters/end_timestamp'
      tags:
        - Ports
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PortDetails'

  /api/kytos/of_stats/v1/{dpid}/flows:
    get:
      summary: Given a switch, list its flows with their latest statistics
      description: Get the latest statistics of all flows of a switch
        identified by ``dpid``. Also provide their attributes and IDs.
      parameters:
        - $ref: '#/components/parameters/dpid'
      tags:
        - Flows
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: List of Flows
                    items:
                      $ref: '#/components/schemas/Flow'

  /api/kytos/of_stats/v1/{dpid}/flows/{ID}:
    get:
      summary: Get up to 60 points of each statistic type for a flow
      description: Return up to 60 evenly-distributed points from ``start``
        to ``end`` (defaults from first sample until current time). Useful for
        plotting graphs.
      parameters:
        - $ref: '#/components/parameters/dpid'
        - $ref: '#/components/parameters/flow_id'
        - $ref: '#/components/parameters/start_timestamp'
        - $ref: '#/components/parameters/end_timestamp'
      tags:
        - Flows
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/FlowDetails'

components:
  schemas:
    Port:
      type: object
      properties:
        mac:
          type: string
          description: MAC address of a switch port
          example: d2:39:59:8d:0c:94
        name:
          type: string
          description: Port name
          example: s2-eth1
        port:
          type: integer
          description: Port number
          example: 1
        rx_bytes:
          type: number
          description: Received bytes per second
          example: 10244268.157941082
        rx_dropped:
          type: number
          description: Packets received and dropped per second
          example: 0.0
        rx_errors:
          type: number
          description: Receiving errors per second
          example: 0.0
        speed:
          type: integer
          description: Maximum port speed in bps
          example: 10000000000
        tx_bytes:
          type: number
          description: Transmitted bytes per second
          example: 10244290.726295035
        tx_dropped:
          type: number
          description: Packets transmitted and dropped per second
          example: 0.0
        tx_erros:
          type: number
          description: Transmitting errors per second
          example: 0.0
        tx_util:
          type: number
          description: Upload bandwidth utilization (0 to 1)
          example: 0.008195432581036029

    PortDetails:
      type: object
      properties:
        data:
          type: object
          properties:
            timestamps:
              type: array
              description: Unix timestamp in seconds of each point
              example: [1508532494, 1508536094, 1508539694]
              items:
                type: integer
            rx_bytes:
              type: array
              description: Received bytes per second
              example: [66647351.252421244117, 9884929.4810, 98803928.7153]
              items:
                type: number
            rx_dropped:
              type: array
              description: Packets received and dropped per second
              example: [0.526738393, 1.98728726227829, 292.872625267282]
              items:
                type: number
            rx_errors:
              type: array
              description: Receiving errors per second
              example: [1234.567890234630672, 5678.9572424680, 12.34574680]
              items:
                type: number
            tx_bytes:
              type: array
              description: Transmitted bytes per second
              example: [2345678967.89456789, 678945.62346, 78906.784562347]
              items:
                type: number
            tx_dropped:
              type: array
              description: Packets transmitted and dropped per second
              example: [670.8978345, 103.691324, 0.0]
              items:
                type: number
            tx_errors:
              type: array
              description: Transmitting errors per second
              example: [56.7834523456, 7.89562346, 987.65765434]
              items:
                type: number
                
    Action:
      type: object
      properties:
        port:
          type: integer
          description: Port number where the flow is installed
          example: 2
        type:
          type: string
          description: Name of an action type
          example: action_output
  
    Flow:
      type: object
      properties:
        actions:
          type: array
          description: Flow action list
          example:
          - {
             "port": 2,
             "type": "action_output"
          }
          items:
            $ref: "#/components/schemas/Action"
        buffer_id:
          type: integer
          description: Buffer identifier
          example: 2333
        cookie:
          type: integer
          description: Opaque controller-issued identifier
          example: 7633
        dl_dst:
          type: string
          description: Ethernet source address
          example: 00:00:00:00:00:01
        dl_src:
          type: string
          description: Ethernet source address
          example: 00:00:00:00:00:02
        dl_type:
          type: integer
          description: Ethernet frame type
          example: 2048
        dl_vlan:
          type: integer
          description: Input VLAN id
          example: 0
        dl_vlan_pcp:
          type: integer
          description: Input VLAN priority
          example: 0
        hard_timeout:
          type: integer
          description: Max time before discarding (seconds)
          example: 0
        id:
          type: string
          description: Flow Identifier
          example: 3b8464f07e0ef1913baa54795b309cfc
        idle_timeout:
          type: integer
          description: Idle time before discarding (seconds)
          example: 0
        in_port:
          type: integer
          description: Input switch port
          example: 1
        nw_dst:
          type: string
          description: IP destination address
          example: 0.0.0.0
        nw_src:
          type: string
          description: IP source address
          example: 0.0.0.0
        priority:
          type: integer
          description: Priority level of flow entry
          example: 0
        stats:
          type: object
          description: Object representing a flow statistic
          properties:
            Bps:
              type: integer
              description: Bytes per second
              example: 0.0
            pps:
              type: integer
              description: Packets per second
              example: 0.0
        table_id:
          type: integer
          description: Table ID of where the flow belongs
          example: 0
        tp_dst:
          type: string
          description: TCP/UDP destination port
          example: 0
        tp_src:
          type: string
          description: TCP/UDP source port
          example: 0
        wildcards:
          type: integer
          description: Wildcards field
          example: 3678435
  
    FlowDetails:
      type: object
      properties:
        data:
          type: object
          description: Flow information
          properties:
            bytes_count:
              type: array
              description: Bytes counter
              example: [66654140, 9930607, 99038495]
              items:
                type: integer
            packet_count:
              type: array
              description: Packet counter
              example: [66747103, 9978767, 98804666]
              items:
                type: integer
            timestamps:
              type: array
              description: Unix timestamp in seconds of each point
              example: [1508532494, 1508536094, 1508539694]
              items:
                type: integer
  parameters:
    dpid:
      in: path
      name: dpid
      required: true
      schema:
        type: string
      description: Switch datapath identifier

    port:
      in: path
      name: port
      required: true
      schema:
        type: integer
        minimum: 1
      description: Switch port number

    start_timestamp:
      in: query
      name: start
      required: false
      schema:
        type: integer
        minimum: 1
      description: Unix timestamp in seconds for first statistics. If not
          specified, use timestamp of the first collected sample.

    end_timestamp:
      in: query
      name: end
      required: false
      schema:
        type: integer
        maximum: 65534
      description: Unix timestamp in seconds for last statistics. If not
        specified, use current timestamp.

    flow_id:
      in: path
      name: ID
      required: true
      schema:
        type: string
        minimum: 1
      description: Flow unique identifier
